version: "3"
services:
  pumbaa-signal-web:
    container_name: pumbaa-signal-web
    build:
      context: .
      args:
        - API_UID=1010
        - API_GID=1010
    environment:
      - PORT=8080 #TODO
      - API_UID=1010
      - API_GID=1010
    ports:
      - "80:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" # TODO delete ?
#      - "./conf:/app/signal-web/conf"
